# Generated by Django 6.0 on 2026-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_models', '0002_rename_uses_packresource_daily_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packresource',
            name='discord_id',
            field=models.BigIntegerField(help_text='Discord user ID', null=True, unique=True),
        ),
    ]
