# Generated by Django 6.0 on 2026-09-05 00:13

from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def migrate_discord_ids(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor"):
    PackResource = apps.get_model("pack_models", "PackResource")

    for resource in PackResource.objects.select_related("player").iterator():
        resource.discord_id = resource.player.discord_id
        resource.save(update_fields=["discord_id"])


class Migration(migrations.Migration):
    dependencies = [("pack_models", "0003_packresource_discord_id")]

    operations = [migrations.RunPython(migrate_discord_ids, atomic=True)]
