# Generated by Django 6.0 on 2026-09-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack_models', '0004_migrate_player_to_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packresource',
            name='discord_id',
            field=models.BigIntegerField(help_text='Discord user ID', unique=True),
        ),
    ]
