# Generated by Django 6.0 on 2026-09-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pack_models', '0005_alter_packresource_discord_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packresource',
            name='player',
        ),
    ]
