# Generated by Django 6.0 on 2026-09-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0018_guildconfig_manual_drop_enabled'),
        ('merchant_app', '0003_globalshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.PositiveIntegerField(help_text='Coins received for each token converted when using /merchant convert_token')),
                ('ball', models.OneToOneField(help_text='The ball to be used as a token.', on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
            ],
            options={
                'db_table': 'tokenconversion',
                'managed': True,
            },
        ),
    ]
