# Generated by Django 5.2.8 on 2026-04-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_player2_set', to='bd_models.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_winner_set', to='bd_models.player')),
            ],
            options={
                'db_table': 'battle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BattleBallRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.OneToOneField(help_text='Ball that you want to ban.', on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
            ],
            options={
                'db_table': 'battleballrestriction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BattleBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0, help_text='Amount of health to add')),
                ('attack', models.IntegerField(default=0, help_text='Amount of attack to add')),
                ('ball', models.OneToOneField(blank=True, help_text='Ball that will receive an increase', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
                ('special', models.OneToOneField(blank=True, help_text='Specials that will receive an increase', null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.special')),
            ],
            options={
                'db_table': 'battlebuff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BattleObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('ballinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.ballinstance')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle_app.battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'battleobject',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['player1_id'], name='battle_player1_fa7291_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['player2_id'], name='battle_player2_faa9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='battle',
            index=models.Index(fields=['winner_id'], name='battle_winner__ad69b7_idx'),
        ),
        migrations.AddIndex(
            model_name='battleobject',
            index=models.Index(fields=['battle_id'], name='battleobjec_battle__c0b453_idx'),
        ),
        migrations.AddIndex(
            model_name='battleobject',
            index=models.Index(fields=['ballinstance_id'], name='battleobjec_ballins_71567e_idx'),
        ),
        migrations.AddIndex(
            model_name='battleobject',
            index=models.Index(fields=['player_id'], name='battleobjec_player__2631d8_idx'),
        ),
    ]
