# Generated by Django 5.2.8 on 2026-04-22 17:25

import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_role_id', models.BigIntegerField(blank=True, help_text='An optional role id to notify users when a boss game starts.', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d{17,20}$'), message='Only Discord Role ID are supported.')])),
            ],
            options={
                'verbose_name_plural': 'BossSettings',
                'db_table': 'bosssettings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BossBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_image', models.ImageField(blank=True, help_text='Image used when the boss will start.', max_length=200, null=True, upload_to='')),
                ('attack_image', models.ImageField(blank=True, help_text='Image used when the boss will attack.', max_length=200, null=True, upload_to='')),
                ('defense_image', models.ImageField(blank=True, help_text='Image used when the boss will defense.', max_length=200, null=True, upload_to='')),
                ('credits', models.CharField(blank=True, help_text='Author of boss arts', max_length=64, null=True)),
                ('ball', models.OneToOneField(help_text='Ball who will be boss', on_delete=django.db.models.deletion.CASCADE, to='bd_models.ball')),
            ],
            options={
                'db_table': 'bossball',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BossPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('deaths', models.PositiveBigIntegerField(default=0)),
                ('damage', models.PositiveBigIntegerField(default=0)),
                ('kills', models.PositiveBigIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'bossplayer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BossHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.PositiveBigIntegerField(default=0)),
                ('dead', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_app.bossball')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_app.bossplayer')),
            ],
            options={
                'db_table': 'bosshistory',
                'managed': True,
            },
        ),
    ]
