# Generated by Django 5.2.8 on 2026-04-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_ballinstance_deleted_and_more'),
        ('boss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosshistory',
            name='ball_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bd_models.ballinstance'),
        ),
    ]
